/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Rustia {
  /**
   * Create a new Rustia instance.
   * ### Example
   * ```javascript
   * const options = {
   *   nodes: [
   *     { name: "my-node", host: "127.0.0.1:2333", secure: false }
   *   ]
   * };
   * const rustia = new Rustia(options);
   * ```
   */
  constructor(options: RustiaOptions)
  /** Returns information about registered nodes. */
  getNodes(): Array<Node>
}

/**
 * It's a structure that manages node connections.
 * ### Example
 * ```
 * {
 *     name: "node-name",
 *     host: "myserver:2333",
 *     secure: true,
 *     is_nodelink: true,
 *     session_id: "session_id",
 * }
 * ```
 */
export interface Node {
  /** Node name */
  name: string
  /** Server address (must include the port) */
  host: string
  /** Whether the server uses a secure connection */
  secure: boolean
  /** If you are using NodeLink, set this option to true. */
  isNodelink?: boolean
  /** Option: Session ID */
  sessionId?: string
}

export interface RustiaOptions {
  nodes: Array<Node>
}
